name: Spring Boot Unit Tests
on:
  pull_request:
    types:
      - opened
    branches:
      - main # main
      - 'dev-*' #dev-new dev-this-is-new
      - 'feat/**' #feat/new feat/newbutton
  workflow_dispatch:
  push:
    branches:
      - main # main
      - 'dev-*' #dev-new dev-this-is-new
      - 'feat/**' #feat/new feat/newbutton
    paths-ignore:
      - '.github/workflows/*'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Set Up JDK 22
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '22'
          cache: maven
      - name: Run Spring Boot Tests
        run: mvn test
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Set Up JDK 22
        uses: actions/setup-java@v4
        with:
            distribution: temurin
            java-version: '22'
            cache: maven
      - name: Build with Maven
        run: mvn clean install
      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
            name: my-artifact
            path: target/*.jar # or path/to/artifact
  deploy:
      needs: build
      runs-on: ubuntu-latest
      steps:
        - name: Get build artifact
          uses: actions/download-artifact@v5
          with:
            name: my-artifact
        - name: Output Contents
          run: ls
        - name: Final code deployed
          run: echo"deployed...."



